# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\interfaceVisual\janelaGraficoResultados.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow_graficoResultados(object):
    def setupUi(self, MainWindow_graficoResultados):
        MainWindow_graficoResultados.setObjectName("MainWindow_graficoResultados")
        MainWindow_graficoResultados.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow_graficoResultados.sizePolicy().hasHeightForWidth())
        MainWindow_graficoResultados.setSizePolicy(sizePolicy)
        MainWindow_graficoResultados.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow_graficoResultados)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.containerFrameDoGrafico = QtWidgets.QFrame(self.centralwidget)
        self.containerFrameDoGrafico.setStyleSheet("")
        self.containerFrameDoGrafico.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.containerFrameDoGrafico.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerFrameDoGrafico.setObjectName("containerFrameDoGrafico")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.containerFrameDoGrafico)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_Grafico = QtWidgets.QGridLayout()
        self.gridLayout_Grafico.setSpacing(0)
        self.gridLayout_Grafico.setObjectName("gridLayout_Grafico")
        self.gridLayout_3.addLayout(self.gridLayout_Grafico, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.containerFrameDoGrafico, 0, 0, 1, 1)
        self.containerFrameDosCheckBoxes = QtWidgets.QFrame(self.centralwidget)
        self.containerFrameDosCheckBoxes.setMinimumSize(QtCore.QSize(160, 0))
        self.containerFrameDosCheckBoxes.setMaximumSize(QtCore.QSize(160, 16777215))
        self.containerFrameDosCheckBoxes.setStyleSheet("")
        self.containerFrameDosCheckBoxes.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.containerFrameDosCheckBoxes.setFrameShadow(QtWidgets.QFrame.Raised)
        self.containerFrameDosCheckBoxes.setObjectName("containerFrameDosCheckBoxes")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.containerFrameDosCheckBoxes)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_CheckBoxes = QtWidgets.QVBoxLayout()
        self.verticalLayout_CheckBoxes.setSpacing(0)
        self.verticalLayout_CheckBoxes.setObjectName("verticalLayout_CheckBoxes")
        self.verticalLayout_3.addLayout(self.verticalLayout_CheckBoxes)
        self.gridLayout.addWidget(self.containerFrameDosCheckBoxes, 0, 1, 1, 1)
        MainWindow_graficoResultados.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow_graficoResultados)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow_graficoResultados.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow_graficoResultados)
        self.statusbar.setObjectName("statusbar")
        MainWindow_graficoResultados.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow_graficoResultados)
        QtCore.QMetaObject.connectSlotsByName(MainWindow_graficoResultados)

    def retranslateUi(self, MainWindow_graficoResultados):
        _translate = QtCore.QCoreApplication.translate
        MainWindow_graficoResultados.setWindowTitle(_translate("MainWindow_graficoResultados", "Melhor CIF de cada rodada"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow_graficoResultados = QtWidgets.QMainWindow()
    ui = Ui_MainWindow_graficoResultados()
    ui.setupUi(MainWindow_graficoResultados)
    MainWindow_graficoResultados.show()
    sys.exit(app.exec_())
